### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by John-Colvin** [comment]
https://github.com/DerelictOrg/DerelictUtil/pull/11

**Comment by John-Colvin** [comment]
I remember why I didn't do this before: there isn't a clfft package for ubuntu. Well, there is, but no use for TravisCI for a long time as it's only in Wily Werewolf (https://launchpad.net/ubuntu/+source/clfft).

Perhaps we can express the necessary steps to install it manually in the .travis.yml file? There are also binaries available at https://github.com/clMathLibraries/clFFT/releases

**Comment by John-Colvin** [comment]
Instead of using the deb package, you might be able to get away with just dumping the contents of `lib64` from https://github.com/clMathLibraries/clFFT/releases/download/v2.6/clFFT-2.6.0-Linux-x64.tar.gz into the root of the package before running dub, which would avoid needing sudo.

**Comment by John-Colvin** [comment]
I think it needs LIBRARY_PATH as well to know where to look at link-time. LD_LIBRARY_PATH handles load-time.

**Comment by 9il** [comment]
Yeah!

**Comment by John-Colvin** [comment]
Awesome. I was worried they didn't have OpenCL installed at all, which would have been a massive pain, but apparently they do.

`sudo: false`?

**Comment by 9il** [comment]
`sudo: false` added

**Pull request merged**
